cloud:
  aws:
    region:
      static: eu-central-1   # Region where you have created the queue. In this example, we have created the queue in 'ap-south-1' region.
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAW5W2MYFD6JPCR6EA
      secret-key: Ir7diXmudCTLmyZnaRlDUt/0hejfPC4C0agoqnr1

logging:
  level:
    com.amazonaws:
      util.EC2MetadataUtils: ERROR
      internal.EC2ResourceFetcher: ERROR
      auth.profile.internal.BasicProfileConfigLoader: ERROR